// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfvllwpyhpmodgjrzmdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmdmxsd3B5aHBtb2RnanJ6bWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzIxNjUsImV4cCI6MjA3MDkwODE2NX0.79JHVJVuthr6ccyQjWlyIsfau5hR-K-PCYB0U_zSu04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});